### ISSUE TITLE
problem to get on webserver j4 site 

### ISSUE THREAD

**Issue by jsr4id** [Digital-Peak/DPDocker#37]
Hi,

i have problem with the j4 webserver site.

localhost:80 seems ok:
![Screenshot 2022-02-03 222136](https://user-images.githubusercontent.com/19953956/152431232-dac812ca-2d43-40ad-972f-1d7d6f54848a.png)

If i click on j3 everthing is fine.
When open the j4 sites i see this.

**Patch release Joomla 4 site with local extensions linked** _localhost/j4_
Just a white site
![Screenshot 2022-02-03 222610](https://user-images.githubusercontent.com/19953956/152431596-7c5a4aa3-71d6-46bd-96aa-80275770a923.png)

**Feature release Joomla 4 site with dev extensions linked** _localhost/dev4_
Errors occurs
![Screenshot 2022-02-03 222649](https://user-images.githubusercontent.com/19953956/152431861-5bad238d-5526-4f33-8cf5-2e267d8b0a4d.png)
![Screenshot 2022-02-03 222658](https://user-images.githubusercontent.com/19953956/152431880-6927bac0-8768-4498-8f28-af79450490f3.png)

**Joomla 4 playground** _localhost/play4_
Also a white site.

SQL Databases looks this:
![Screenshot 2022-02-03 222849](https://user-images.githubusercontent.com/19953956/152432047-087747b0-fec8-4f84-a608-70404b47d78f.png)

I've a testsystem with windows WSL, Ubuntu 20.04 and Docker Desktop
___

1. Any suggestion for this issue?
2. After lot of hours with dpdocker, i just didn't figure out how i can link my extension. Especially when it is stored on the windows file system. Where are the settings for linking a component project folder? (e.g d:/projects/com1)

**Comment by laoneo** [comment]
How did you start the container? Perhaps you have missed some environment variables.

**Comment by jsr4id** [comment]
cd DPDocker
webserver/run.sh

**Comment by laoneo** [comment]
And you are on Linux?

**Comment by jsr4id** [comment]
Im on a windows machine with WSL support and Docker Desktop. 
I start the webserver in the lunix cli.

**Comment by laoneo** [comment]
When you started the web server can you extract a [Joomla download package](https://downloads.joomla.org/cms/joomla4/4-0-6/Joomla_4-0-6-Stable-Full_Package.zip?format=zip) to the folder webserver/www/test? Then open the link localhost/test and make the normal installation. Do you succeed?
When the web server started what for a PHP version does it show?

**Comment by jsr4id** [comment]
Download to test and open it work
Webserver starts with php 8.0.28
![Screenshot 2022-02-04 174710](https://user-images.githubusercontent.com/19953956/152568634-9496fc3d-7981-4ba8-a0c9-b708fa832707.png)
s

**Comment by jsr4id** [comment]
I did a new clean installation of DPDocker.
I started the webserver and webserver was not reachable. All the other localhost ports are working (mysql, ftp,...)
I was  confused that the webserver starts on port 443
![Screenshot 2022-02-04 175313](https://user-images.githubusercontent.com/19953956/152572549-9b1e011a-fcaf-483f-bdab-7a6bebc9dc2b.png)

So i just commend out the webserver port 443 line in webserver/docker-compose.yml
![Screenshot 2022-02-04 181623](https://user-images.githubusercontent.com/19953956/152573261-9a4a1754-68a5-4f71-9f8c-72fe51b96dbd.png)

After that, webserver was started with port 80 and i can browse to that. 
After comment the line in again, the container still starts with 443 and oddly enough, only localhost:80 works yet.
I dont understand that? Maybe the port 80 was blocked?

Anyway, localhost/j4 just does not work.
BUT, now an other error occurs.
![Screenshot 2022-02-04 182439](https://user-images.githubusercontent.com/19953956/152574604-db6d2235-0f2d-4a04-9c29-605260eac2b0.png)

**By the way, localhost/play4 seems working**

**Comment by jsr4id** [comment]
**Little update:**
The containers are now running. I think there was a problem with `images/build.sh`.

**Another Question:**
When I git clone the repo, it is installed at `home/<username>`. Because this is the home directory for wsl.
In the description, the directory `/usr/src/Projects` should be used. So I clone the DPAttachements repo as well. DPDocker and DPAttachements lie next to each other at `home/<username>`. Joomlas discover does not work for this because of the path.
Where I can change the mapped directory for my extension?

**Comment by laoneo** [comment]
Please open a new issue when there is a new problem. Marking this as closed as the issue got solved.
