### ISSUE TITLE
Command docker-compose without hyphen

### ISSUE THREAD

**Issue by astridx** [Digital-Peak/DPDocker#48]
Do you like to support the new syntax? See: https://www.heise.de/ratgeber/FAQ-Container-mit-Docker-und-die-Feinheiten-von-Docker-Compose-7138016.html

**Comment by laoneo** [comment]
you mean `docker compose`?

**Comment by astridx** [comment]
Yes

**Comment by laoneo** [comment]
From which Docker version is this supported? Are you doing a pr?

**Comment by astridx** [comment]
Since Compose V2 (https://docs.docker.com/compose/reference/)

**Comment by laoneo** [comment]
As the compose command of docker is not available in Ubuntu 22 I will put this one on hold. When it is available then we can migrate to v2, for now we stick to v1.

**Comment by laoneo** [comment]
Can you have a look on https://github.com/Digital-Peak/DPDocker/pull/62. it should change to docker compose v2.
